### ISSUE TITLE
null-safety migration

### ISSUE THREAD

**Issue by calvintam236** [ko-htut/octicons#1]
Looks like this package has not migrated for null-safety. Flutter 2.2 is out today with null-safety ENABLED by default. We need null-safety migration ASAP.

**Comment by yc-codes** [comment]
This Can fix #2 

Till then you can use this like
```yaml
    octicons_icon:
        git:
            url: git://github.com/yc-codes/octicons_icon.git
            ref: master
```
